### PR TITLE
Loading Screen

### PR DESCRIPTION
**Pull request by OJarrisonn**
This PR introduce a new macro `loading_screen!` that can be used to spawn a loading screen while the encapsulated code is running.

This macro syntax is:
```rs
terminal = loading_screen! { terminal, "Loading stuff" => {
    // do something take takes long to execute
}}
```

It takes ownership of the terminal, asks for a title for the loading screen and then a piece of code to execute. It will then spawn a new thread where the loading screen will be rendered (this adds support for some parallel animation to be execute in the loading screen). Immediately the given code block starts to run, once it finishes the thread will be finished and the terminal is returned to be then recovered by the main thread.

Some key notes:
- The code block will be executed in the same scope where `loading_screen!` is called
- The loading screen won't stop rendering if the given code block returns early or panics, neither give the terminal back  

One solution for the later bullet point would be to treat the code as a closure so it would never be able to return early. I still don't know exactly how to address panics (do they actually need to be addressed?)

### CODE REVIEW

**Comment by davidbtadokoro** [comment]
Hi @OJarrisonn, and thank you for this PR!

Following our offline discussion, I made some "stress tests" to see if the point you've brought about possibly having an orphan thread that would silently lock the terminal in case the inside code block panicked/returned earlier.

### What I've found

1. The compiler protects us from introducing explicit `panic!`s or `return`s, because, when expanding the macro, the compiler detects that the trailing part of the code will be unreachable. This is very nice as it protects us from introducing these naive bugs. **NOTE** that, FWIU, unreachable codes are warnings, but our limiting sets it as an error (as it should), so I assume this will be caught as an error in all cases.
2. I forced a `panic!` situation by disconnecting from the network and refreshing the mailing lists. This results in the whole execution aborting, which (again) is good for us as it prevents the terminal from silently locking.

### Problem

The only "problem" I've found is that the terminal cursor gets invisible when a panic happens in this context. I'm unsure if this is particular to my terminal emulator, but it is consistent. A simple `ctrl+L` solves it. It is important to stress that this isn't a big trouble, like when the terminal melts due to not being restored before panicking. My hypothesis is that the loading screen "steals" the cursor (???)

### Conclusion

I think we are safe to merge this as is (only modifying to solve merge conflicts, of course) and maybe opening an issue about the cursor if it ends up being consistent across other setups (I invite anyone to test it and bring feedback about it).

Nevertheless, this is a marvelous change that will greatly improve the project!

**Obs.:** Whilst I wait for your feedback, I will start trying to integrate PR #61 on top of this for a neater spinner.

**Comment by OJarrisonn** [comment]
I am worried about the `?` operator. It won't raise any unreachable code error, but might finishes the scope early, so it might exit the function without removing the loading screen.

For instance at `src/handler.rs:72`

```rs
                terminal = loading_screen! {
                    terminal,
                    format!("Fetching patchsets from {}", target_list) => {
                        patchsets_state.fetch_current_page()?;
                    }
                };
```

If `fetch_current_page()` fails the loading screen won't be removed

**Comment by davidbtadokoro** [comment]
Sorry if I misinterpreted your answer, but the test I did actually forced `fetch_current_page()` to fail, and the execution ended as a whole. That was what I said in point 2, but maybe I misled you into the notion that the function underneath hit an explicit `panic!`.

Try launching patch-hub, then disconnecting from the network and selecting any list. This causes the function to call `bail!` in [here](https://github.com/kworkflow/patch-hub/blob/fee100cb0c9334b3811d2783ee5f75e73341ae3b/src/app/screens/latest.rs#L43). From my tests, it consistently crashes the app as a whole.

**Comment by davidbtadokoro** [comment]
Hey @OJarrisonn, I've made some small adaptations, as mentioned, and integrated the loading spinner ideas of @gabrielsrd PR #61. The results can be checked at the branch `feat-loading-screen-w-spinner`. To test it, do

```
git remote add upstream https://github.com/kworkflow/patch-hub.git # (if you don't already have it)
git fetch upstream
git checkout upstream/feat-loading-screen-w-spinner
```

then run `cargo run` normally.

**Comment by OJarrisonn** [comment]
If that particular case works, then it's alright to me

**Comment by davidbtadokoro** [comment]
Ok! Change merged into the unstable branch :+1:

**Pull request closed without merging**
